# *****************************************************************
# 🚀 PROJECT CONFIG                                               +
# *****************************************************************
# IMPORTANT: This allows you to **overwrite/add** config
# values all form one place.
#
# It is intended to define variables that
# do not change between environments

app:
  # TODO: change this to your project name
  name: "LaravelFilamentTemplate"
  # TODO: change this to your project id
  id: "lft"

  fallback_locale: en
  faker_locale: en_US
  timezone: CET



# *****************************************************************
# 🌐 DOMAIN CONFIG                                                +
# *****************************************************************
# IMPORTANT: Make sure to read ## Custom Domains in the README.md

_domain_config:
  base_domain: 021-fast.fun
  acm_certificate_arn: arn:aws:acm:us-east-1:202533508550:certificate/6cc7d742-c495-4426-953a-9cc729e03886
  hostedZoneId: Z01423412GJ8N7Z1DA13O

  # custom prefix per environment
  env_domain_prefix:
    production: ${self:custom.app_id}.
    '*': ${self:custom.env}-${self:custom.app_id}.



# *****************************************************************
# 🛫 DEPLOYMENT SETTING                                           +
# *****************************************************************
# !IMPORTANT: this gets parsed by the serverless framework
# see: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml

_deployment:
  aws:
    # NOTE: Config you may not need to change
    php_runtime: php-83
    default_region: eu-central-1


# *****************************************************************
# 🔧 ENVIRONEMT DEBUG                                             +
# *****************************************************************
# !IMPORTANT: this gets parsed by the serverless framework
# see: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
_env_debug_mode:
  production: false
  '*': true
