# *****************************************************************
# 🚀 PROJECT CONFIG                                               +
# *****************************************************************
# IMPORTANT: This allows you to **overwrite/add** config
# values all form one place.
#
# It is intended to define variables that
# do not change between environments

app:
  name: &app_name "HDS AiCoach"
  # IMPORTANT: this must be unique per project and needs to be in wrapped QUOTES
  id: &app_id "hds-ai-coach"



# *****************************************************************
# 🌐 DOMAIN CONFIG                                                +
# *****************************************************************
# IMPORTANT: Make sure to read ## Custom Domains in the README.md

_domain_config:
  base_domain: 021-fast.fun
  acm_certificate_arn: arn:aws:acm:us-east-1:202533508550:certificate/6cc7d742-c495-4426-953a-9cc729e03886
  hostedZoneId: Z01423412GJ8N7Z1DA13O

  # custom prefix per environment
  stage_domain_prefix:
    production: ${self:custom.app_id}.
    '*': ${self:provider.stage}-${self:custom.app_id}.



# *****************************************************************
# 🛫 DEPLOYMENT SETTING                                           +
# *****************************************************************
# !IMPORTANT: this gets parsed by the serverless framework
# see: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml

_deployment:
  aws:
    # NOTE: Config you may not need to change
    php_runtime: php-83
    default_region: eu-central-1



# *****************************************************************
# 🔧 BASE ENV VARIABLES                                         +
# *****************************************************************
# !IMPORTANT: this gets parsed by the serverless framework
# see: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml

_environment_base: &base_env
  # APPLICATION CORE SETTINGS
  APP_NAME: *app_name
  APP_ID: *app_id
  APP_KEY: bref-ssm:/${self:custom.app_id}/app_key
  APP_ENV: ${self:provider.stage}
  MAINTENANCE_MODE: ${param:maintenance, null}

  # LOCALIZATION SETTINGS
  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  APP_FAKER_LOCALE: en_US

  # URL & DOMAIN CONFIGURATION
  APP_URL: https://${self:custom.default_domain_config.domain_name}

  # DATABASE CONFIGURATION
  DB_CONNECTION: pgsql
  DB_PORT: 5432
  DB_DATABASE: ${self:custom.project_config.app.id}-${self:provider.stage}
  DB_PASSWORD: bref-ssm:/prod-primary-projects/rds-password
  DB_HOST: bref-ssm:/prod-primary-projects/rds-endpoint
  DB_USERNAME: bref-ssm:/prod-primary-projects/rds-user

  # AWS CONFIGURATION
  AWS_PROJECT_DEFAULT_REGION: eu-central-1
  AWS_USE_PATH_STYLE_ENDPOINT: true
  OPENAI_API_KEY: bref-ssm:/prod-primary-projects/openai-api-key

  # STORAGE & FILESYSTEM
  FILESYSTEM_DRIVER: s3
  FILESYSTEM_DISK: public
  FILAMENT_FILESYSTEM_DISK: public
  PUBLIC_AWS_BUCKET: ${construct:public_storage.bucketName}
  PRIVATE_AWS_BUCKET: ${construct:private_storage.bucketName}
  CACHE_STORE: database
  DB_CACHE_CONNECTION: pgsql
  DB_CACHE_LOCK_CONNECTION: pgsql

  # SESSION CONFIGURATION
  SESSION_DRIVER: Cookie

  # SYSTEM SERVICES
  BROADCAST_CONNECTION: log
  LOG_CHANNEL: stderr
  QUEUE_CONNECTION: sqs
  SQS_QUEUE: "${construct:jobs.queueUrl}"

  # MAIL SETTINGS
  RESEND_API_KEY: bref-ssm:/prod-primary-projects/resend-api-key
  MAIL_MAILER: resend
  MAIL_FROM_ADDRESS: hello@021-fast.fun
  ADMIN_MAIL_ADDRESS: admin@021-factory.com
  MAIL_FROM_NAME: *app_name

  # Notification Settings
  HEALTH_SLACK_WEBHOOK_URL: bref-ssm:/prod-primary-projects/health-slack-webhook-url

  # FRONTEND CONFIGURATION
  VITE_APP_NAME: ${self:custom.app_id}

# misc
# ...

# *****************************************************************
# 🔧 ENVIRONMENT SPECIFIC VARIABLES                                +
# *****************************************************************
# !IMPORTANT: this gets parsed by the serverless framework
# see: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml

_environments:
  production:
    <<: *base_env
    APP_DEBUG: false
    ALLOW_ROBOTS: true

  staging:
    <<: *base_env
    APP_DEBUG: true
    ALLOW_ROBOTS: false

  development:
    <<: *base_env
    APP_DEBUG: true
    ALLOW_ROBOTS: false

  testing:
    <<: *base_env
    APP_DEBUG: false
    ALLOW_ROBOTS: false

  '*':
    <<: *base_env
    APP_DEBUG: false
    ALLOW_ROBOTS: false



# *****************************************************************
# 🔧 GITHUB VARIABLES                                             +
# *****************************************************************
# secret keys for github, key represents the name
# and the value the enpass field name

github:
  secrets:
    AWS_ACCESS_KEY_ID:GH_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:GH_AWS_SECRET_ACCESS_KEY

