service: ${self:custom.project_config.app.id}

provider:
  name: aws
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'eu-central-1'} # this region also needs to be registered in ACM as well
  environment: ${switch(${self:provider.stage}, ${self:custom.project_config._environments})}

  iam:
    role:
      statements:
        - Effect: Allow
          Action: ssm:GetParameters
          Resource: '*'
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:ListBucket
            - s3:PutObjectAcl
          Resource:
            - ${construct:public_storage.bucketArn}
            - Fn::Join: ['', ['${construct:public_storage.bucketArn}', '/*']]
            - ${construct:private_storage.bucketArn}
            - Fn::Join: ['', ['${construct:private_storage.bucketArn}', '/*']]

package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'
    - '!database/*.sqlite'
    - '!.phpunit.cache/**'
    - '!.idea/**'
    - '!.vscode/**'
    - '!.serverless/**'
    - '!.env*'
    - '!.phpunit.result.cache'
    - '!npm-debug.log'
    - '!vite.config.*'
    - '!docker/**'
    - '!docker-compose.yml'
    - '!.github/**'
    - '!.gitattributes'
    - '!.editorconfig'
    - '!README.md'
    - '!.env*'
    - '!bin/**'
    - '!.cursor/**'

functions:
  web:
    handler: public/index.php
    runtime: ${self:custom.project_config._deployment.aws.php_runtime}-fpm
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    events:
      - httpApi: '*'

  artisan:
    handler: artisan
    runtime: ${self:custom.project_config._deployment.aws.php_runtime}-console
    timeout: 720
    events:
      - schedule:
          rate: rate(1 minute)
          input: '"schedule:run"'
          enabled: ${self:provider.environment.ENABLE_SCHEDULER}

constructs:
  website:
    type: server-side-website
    domain: ${self:custom.default_domain_config.domain_name}
    certificate: ${self:custom.default_domain_config.acm_certificate_arn}
    assets:
      "/build/*": "public/build"
      "/favicon.ico": public/favicon.ico
      "/js/*": "public/js"
      "/css/*": "public/css"

    # add here any file or directory that needs to be served from S3
    # Laravel uses some headers that are not in CloudFront's default whitelist.
    # To add any, we need to list all accepted headers to pass through.
    # https://github.com/getlift/lift/blob/master/docs/server-side-website.md#forwarded-headers
    forwardedHeaders:
      - Accept
      - Accept-Language
      - Content-Type
      - Origin
      - Referer
      - User-Agent
      - X-Forwarded-Host
      - X-Requested-With
      - X-Csrf-Token
      - X-Livewire
      - X-Inertia

  jobs:
    type: queue
    worker:
      handler: Bref\LaravelBridge\Queue\QueueHandler
      runtime: ${self:custom.project_config._deployment.aws.php_runtime}
      timeout: 900
      # limit concurrency to 1
      maxConcurrency: 1
      reservedConcurrency: 1

  private_storage:
    type: storage

  public_storage:
    type: storage
    extensions:
      bucket:
        Properties:
          PublicAccessBlockConfiguration:
            BlockPublicAcls: false
            BlockPublicPolicy: false
            IgnorePublicAcls: false
            RestrictPublicBuckets: false
          OwnershipControls:
            Rules:
              - ObjectOwnership: BucketOwnerPreferred
          CorsConfiguration:
            CorsRules:
              - AllowedOrigins: ['*']
                AllowedHeaders: ['*']
                AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
                MaxAge: 3000
                ExposedHeaders:
                  - x-amz-server-side-encryption
                  - x-amz-request-id
                  - x-amz-id-2

resources:
  Resources:
    Route53Record:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ${self:custom.default_domain_config.hostedZoneId}
        Name: ${self:custom.default_domain_config.domain_name}
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # CloudFront's hosted zone ID (constant)
          DNSName: ${construct:website.cname}

plugins:
  - ./vendor/bref/bref
  - serverless-lift
  - serverless-plugin-utils

custom:
  project_config: ${file(project.yml)}

  # NOTE: Hacky switch statement to set the domain prefix for the environment
  domain_prefix: ${switch(${self:provider.stage}, ${self:custom.project_config._domain_config.stage_domain_prefix})}

  app_id: ${self:custom.project_config.app.id}

  default_domain_config:
    base_domain: ${self:custom.project_config._domain_config.base_domain}
    domain_name: ${self:custom.domain_prefix}${self:custom.default_domain_config.base_domain}
    acm_certificate_arn: ${self:custom.project_config._domain_config.acm_certificate_arn}
    hostedZoneId: ${self:custom.project_config._domain_config.hostedZoneId}
