service: laravel
useDotenv: true

provider:
  name: aws
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'eu-central-1'} # this region also needs to be registered in ACM
  environment:
    MAINTENANCE_MODE: ${param:maintenance, null}

    QUEUE_CONNECTION: sqs
    SQS_QUEUE: ${construct:jobs.queueUrl}

  iam:
    role:
      statements:
        - Effect: Allow
          Action: ssm:GetParameters
          Resource:
            - '*'

        - Effect: Allow
          Action: s3:*
          Resource:
            - arn:aws:s3:::${env:PROJECT_AWS_BUCKET}
            - arn:aws:s3:::${env:PROJECT_AWS_BUCKET}/*

package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'
    - '!database/*.sqlite'

functions:
  web:
    handler: public/index.php
    runtime: php-83-fpm
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    events:
      - httpApi: '*'

  artisan:
    handler: artisan
    runtime: php-83-console
    timeout: 720 # in seconds
    # Uncomment to also run the scheduler every minute
    # events:
    #     - schedule:
    #         rate: rate(1 minute)
    #         input: '"schedule:run"'

plugins:
  - ./vendor/bref/bref # to handle laravel
  - serverless-dotenv-plugin # To load env files based on stage
  - serverless-domain-manager # To create custom domains
  - serverless-lift # SQS Queue creating

constructs:
  jobs:
    type: queue
    worker:
      handler: Bref\LaravelBridge\Queue\QueueHandler
      runtime: php-83
      timeout: 900 # 15 min
custom:
  dotenv:
    path: .env.${self:provider.stage}
    logging: false
    required:
      file: true
      env:
        - APP_DOMAIN
        - PROJECT_AWS_ACM_CERTIFICATE_ARN
        - PROJECT_AWS_BUCKET

  customDomain:
    domainName: ${env:APP_DOMAIN}
    certificateArn: ${env:PROJECT_AWS_ACM_CERTIFICATE_ARN}
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: regional
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: true
    basePath: ''
