name: Deploy Branch

on: [ push ]

concurrency:
  group: deployment

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--no-dev --no-interaction --prefer-dist --optimize-autoloader"

      - name: Run Filament Optimizations
        run: |
          php artisan filament:optimize-clear
          php artisan filament:optimize
          php artisan config:clear
          php artisan view:clear   
          php artisan route:clear

      - name: Serverless Deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "./bin/deploy.sh"
          entrypoint: /bin/bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
