name: Tests

on: [ push ]

jobs:
  tests:
    name: Application Operational Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ankane/pgvector
        env:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql, bcmath, soap, intl, gd, exif, iconv, redis
          coverage: none

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install NodeJS dependencies
        run: |
          npm install
          npm install -g vite

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare Application
        run: |
          php artisan config:clear
          php artisan storage:link
          npm run build

      - name: Setup Vector Extension
        run: |
          PGPASSWORD=root psql -h localhost -p 5433 -U root -d testing -c 'CREATE EXTENSION IF NOT EXISTS vector;'

      - name: Migrations
        run: php artisan migrate --force -v

      - name: PEST
        run: php artisan test --parallel
